server:
  port: 8807
spring:
  application:
    name: dubbo-spring-boot-star
  thymeleaf:
      cache: true
      mode: LEGACYHTML5
      encoding: UTF-8
      servlet:
        content-type: text/html
  mvc:
    pathmatch:
      use-suffix-pattern: true


