server:
  port: 8806
spring:
  application:
    name: dubbo-spring-boot-star
  thymeleaf:
      cache: false
      mode: LEGACYHTML5
      encoding: UTF-8
      servlet:
        content-type: text/html
  mvc:
    pathmatch:
      use-suffix-pattern: true
  dubbo:
    protocol:
      id: dubbo
      name: dubbo
      port: 20881
      status: server
    server: true
    registry: N/A



