spring:
  application:
    name: dubbo-spring-boot-star
  redis:
      host: 60.205.182.2
      password: caoxing123++.
      lettuce:
        pool:
          max-active: 20
          max-idle: 20
          min-idle: 5
  dubbo:
    protocol:
      id: dubbo
      name: dubbo
      port: 20881
      status: server
#      serialization: kryo
    server: true
    registry: N/A

star:
  prefix:
    content: content;
