version: '3.1'
services:
  rabbitmq:
    restart: always
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: caoxing123++.
    volumes:
      - /usr/local/rabbit/data:/var/lib/rabbitmq